In [1]:
from sklearn.datasets import load_iris
import pandas as pd

iris =load_iris()

In [19]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2)
from sklearn.svm import SVC
sv=SVC()
from sklearn.ensemble import RandomForestClassifier
fr= RandomForestClassifier()
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.tree import DecisionTreeClassifier
dd=DecisionTreeClassifier()

In [20]:
l_score=cross_val_score(LogisticRegression(),iris.data,iris.target)
l_score

/Users/ishashree/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [21]:
l_score.mean()

0.9733333333333334

In [22]:
p_score=cross_val_score(SVC(),iris.data,iris.target)
p_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [23]:
p_score.mean()

0.9666666666666666

In [24]:
o_score=cross_val_score(RandomForestClassifier(n_estimators=90),iris.data,iris.target)
o_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [25]:
o_score.mean()

0.9666666666666668

In [27]:
t_score=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
t_score

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [28]:
t_score.mean()

0.9600000000000002